# Generated by Django 6.0.1 on 2026-01-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('author', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('title', models.TextField(max_length=100)),
                ('synopsis', models.TextField(max_length=500)),
            ],
        ),
    ]
