# Generated by Django 6.0.1 on 2026-01-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_author_book_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='horror', max_length=40),
        ),
    ]
